feat: GameObject.GetLocalIdentifierInFile
StansAssets/com.stansassets.foundation pull request #66
Opened 2020-10-08 22:36 UTC by stan-osipov

## Purpose of this PR
GameObject.GetLocalIdentifierInFile  extesions method added.

2020-10-08 23:08 UTC, PavelKlym requested changes
Everything cool, thanks for the insanely useful extension method!
Minor spelling bug detected.

And I thought about the same method for Component/MonoBehaviour maybe?

2020-10-08 23:08 UTC, PavelKlym commented on Runtime/Extensions/UnityEngine/GameObjectExtensions.cs
> +        /// <param name="go">GameObject tou want to check</param>
```suggestion
        /// <param name="go">GameObject you want to check</param>
```

2020-10-08 23:09 UTC, stan-osipov commented
Yep make sense, will do updates shortly :)

2020-10-11 14:20 UTC, PavelKlym approved these changes
Great foundation updates, thanks!

2020-10-11 14:20 UTC, merged