feat: List extension: fast remove method by swap elements
StansAssets/com.stansassets.foundation pull request #74
Opened 2021-07-15 17:38 UTC by Yurii-Tor

## Purpose of this PR
Fast method for removing elements from List implemented.

This feature is often on demand. It changes an order of elements inside the list, so not recomended if order matters. Instead of that LinkedList may be used if it feats needs (it's not an IList type)

## Testing status

 - No tests have been added.

### Manual testing status
Tested in Unity Editor. See link below:
https://share.getcloudapp.com/RBulD2kG

## Comments to reviewers
Notice that 'Remove' method deletes only one element, so the predicate evaluation deletes only the first founded. If you need to delete all evaluated elements, use RemoveAll method, which is also fast and doesn't allocate additional resources.

2021-07-16 09:39 UTC, stan-osipov requested changes
Looks good.
But please convert this test:

> Tested in Unity Editor. See link below:
> https://share.getcloudapp.com/RBulD2kG

To the actual Uini test.

2021-07-20 09:28 UTC, stan-osipov commented
@Yurii-Tor any luck with the test?

2021-07-20 17:57 UTC, Yurii-Tor commented
> @Yurii-Tor any luck with the test?

I'm working on it now. Just started

2021-07-21 09:43 UTC, stan-osipov requested changes
Super minor naming requets.
Thank you for the tests.

2021-07-21 11:56 UTC, Yurii-Tor commented on Tests/Editor/Extensions/CSharpTests.cs
> +    public class CSharpTests {
Ok. No problem. I was confused by the file structure and names.
Thanks for reply! =)

2021-07-26 16:56 UTC, stan-osipov approved these changes
lovely!

2021-07-26 16:56 UTC, merged