feat: Support pooling of YieldInstruction for Coroutines #92
StansAssets/com.stansassets.foundation pull request #94
Opened 2022-05-09 11:29 UTC by AlexWargon

## Purpose of this PR

## Testing status

* No tests have been added.
* Includes unit tests.
* Includes performance tests.
* Includes integration tests.

### Manual testing status

## Comments to reviewers

2022-05-09 15:08 UTC, PavelKlym requested changes
I like overall API, but some impl are questionable. Let's discuss!

2022-05-10 09:10 UTC, AlexWargon commented on Runtime/Async/Coroutine/Pooled YieldInstruction/YieldPool.cs
> +        }
It's faster then typeof(T)

2022-05-10 10:02 UTC, PavelKlym requested changes
LGTM! Just let's format everything with Rider.

2022-05-10 10:10 UTC, PavelKlym requested changes
Some feedback sent after review.

2022-05-10 10:10 UTC, PavelKlym commented on Runtime/Async/Coroutine/Pooled YieldInstruction/YieldPool.cs
> +        private static Dictionary<Type, DefaultPool<PooledYieldInstruction>> m_instructions;
```suggestion
        private static Dictionary<Type, ObjectPool<PooledYieldInstruction>> m_instructions;
```
Please replace DefaultPool with ObjectPool.

2022-05-10 10:10 UTC, PavelKlym commented on Runtime/Async/Coroutine/Pooled YieldInstruction/PooledYieldInstruction.cs
> +    public class PooledYieldInstruction : CustomYieldInstruction
```suggestion
    internal abstract class PooledYieldInstruction : CustomYieldInstruction 
```

2022-05-25 09:19 UTC, PavelKlym approved these changes
LGTM! Great feature and nice implementation.

2022-05-25 09:19 UTC, merged